//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// YEYTotalProject.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_YEYTOTALPROJECT_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DLG_CALENDAR                130
#define IDD_DLG_FILEIO                  132
#define IDD_DLG_POSITION                136
#define IDD_DLG_POSITION_CHILD          138
#define IDB_GREENBUTTOn                 143
#define IDD_DLG_BUTTON                  145
#define IDB_BITMAP_GREEN                147
#define IDB_BITMAP_RED                  148
#define IDB_BITMAP_TEST1                149
#define IDB_BITMAP_TEST2                150
#define IDB_RADIO_OFF                   152
#define IDB_RADIO_ON                    153
#define IDB_CHECK_ON                    154
#define IDB_CHECK_OFF                   155
#define IDC_TREE_CONTROL                1000
#define IDC_MONTHCALENDAR               1001
#define IDC_DATETIMEPICKER1             1002
#define IDC_BTN_GET_DATE                1003
#define IDC_EDIT_PRINTDATE              1004
#define IDC_BTN_GET_MCDATE              1005
#define IDC_EDIT_PRINTMCDATE            1006
#define IDC_EDIT_BG_R                   1007
#define IDC_EDIT_BG_G                   1008
#define IDC_EDIT_BG_B                   1009
#define IDC_RADIO_BACKGROUND            1010
#define IDC_RADIO_CALENDAR_BK           1011
#define IDC_RADIO_CALENDAR_TEXT         1012
#define IDC_RADIO_CALENDAR_TITLE_BG     1013
#define IDC_RADIO_CALENDAR_TITLE_TEXT   1014
#define IDC_BUTTON_CHANGE_COLOR         1015
#define IDC_BTN_CHANGE_COLOR_CAL        1016
#define IDC_BTN_OPENFILE                1016
#define IDC_EDIT_FILE_FULLPATH          1017
#define IDC_EDIT_FILE_FILEPATH          1018
#define IDC_EDIT_FILE_FILEEXT           1019
#define IDC_EDIT_FILE_FILETITLE         1020
#define IDC_EDIT_FILE_FILEREADONLY      1021
#define IDC_EDIT_FILE_FILESTARTPOS      1022
#define IDC_EDIT_FILE_FILENEXTFILENAME  1023
#define IDC_BTN_OPENMULTIFILE           1024
#define IDC_LIST_MULTI_SELECTED         1025
#define IDC_EDIT_FILE_EXCEPTEXT         1026
#define IDC_EDIT_FILE_EXSISTCHECK       1027
#define IDC_EDIT_FILE_EXSISTCHECK2      1028
#define IDC_BTN_SAVE_TXT                1029
#define IDC_BTN_FOLDER_PATH             1030
#define IDC_RADIO_TXT_FORMAT_8          1031
#define IDC_RADIO_TXT_FORMAT_16_B       1032
#define IDC_RADIO_TXT_FORMAT_16_L       1033
#define IDC_RADIO_TXT_FORMAT_32_B       1034
#define IDC_RADIO_TXT_FORMAT_32_L       1035
#define IDC_STATIC_POSITION_PRINT       1035
#define IDC_RADIO_TXT_FORMAT_           1036
#define IDC_DLG_SIZE_PRINT              1036
#define IDC_EDIT_FOLDER_PATH            1037
#define IDC_RADIO_LOAD_METHOD1          1038
#define IDC_RADIO_LOAD_METHOD2          1039
#define IDC_BTN_OPEN_DATA               1040
#define IDC_EDIT_OPEN_LOADDATA          1041
#define IDC_BTN_WRITE_DATA              1042
#define IDC_BTN_SAVE_SPECIFIC_POS       1042
#define IDC_BTN_WRITE_CONTINUEDATA      1043
#define IDC_EDIT_WIDTH_MAIN             1043
#define IDC_EDIT_ACCUMULATE_FILE        1044
#define IDC_EDIT_HEIGHT_MAIN            1044
#define IDC_BTN_COPY_1                  1045
#define IDC_BTN_SAVE_SPECIFIC_POS_CLIENT 1045
#define IDC_EDIT_FILECOPY_SRC           1046
#define IDC_EDIT_WIDTH_CLLENT           1046
#define IDC_EDIT_FILECOPY_DST           1047
#define IDC_EDIT_HEIGHT_CLIENT          1047
#define IDC_BTN_COPY_2                  1048
#define IDC_DLG_POSITION_PRINT          1048
#define IDC_RADIO_BACK_DRAW_1           1049
#define IDC_RADIO_BACK_DRAW_2           1050
#define IDC_BACKGROUND_R                1051
#define IDC_BTN_CHANGE_DLG_SIZE         1052
#define IDC_EDIT_DLGSIZE_X              1053
#define IDC_EDIT_DLGSIZE_Y              1054
#define IDC_BTN_CHANGE_DLG_CLIENT_SIZE  1055
#define IDC_EDIT_DLGSIZE_CLIENT_X       1056
#define IDC_EDIT_DLGSIZE_CLIENT_Y       1057
#define IDC_BACKGROUND_G                1058
#define IDC_BACKGROUND_B                1059
#define IDC_BTN_CHANGE_BACKGROUND_COLOR 1060
#define IDC_BTN_DOMODAL_OPEN            1061
#define IDC_BTN_NEW_CREATE_OPEN         1062
#define IDC_BACKGROUND_TEXT_R           1063
#define IDC_BACKGROUND_TEXT_G           1064
#define IDC_BACKGROUND_TEXT_B           1065
#define IDC_BTN_CHANGE_TEXT_COLOR       1067
#define IDC_BUTTON1                     1069
#define IDC_CHECK_CLICK_COLOR           1069
#define IDC_BTN_IMG_INPUT               1070
#define IDC_CHECK_COLOR_CHANGE          1071
#define IDC_COMBO_IMAGE_LOC             1074
#define IDC_RADIO1                      1075
#define IDC_RADIO2                      1076
#define IDC_RADIO3                      1077
#define IDC_RADIO4                      1078
#define IDC_CHECK1                      1079

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
